[build]
functions = "netlify/functions"
command = "npx vite build"
publish = "dist"

[build.environment]
SECRETS_SCAN_OMIT_PATHS = ".env,.env.example"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/webhook-checkin/:userId/:webhookToken"
to = "/.netlify/functions/webhook-proxy?userId=:userId&webhookToken=:webhookToken"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200